test_nf: test_nf_1 test_nf_2 test_nf_3 test_nf_7 test_nf_11 test_nf_19 test_nf_43 test_nf_67 test_nf_163 test_nf_23 test_nf_31 test_nf_47 test_nf_59 test_nf_71 test_nf_79 test_nf_83 test_nf_5 test_nf_14 test_nf_21 test_nf_95 test_nf_6 test_nf_10 test_nf_13 test_nf_15 test_nf_17 test_nf_22 test_nf_35 test_nf_39 test_nf_42 test_nf_51 test_nf_55 test_nf_87 test_nf_91
	@echo "test_nf finished"

test_nf_1: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=4; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=1; prog=makenf_loop; $(check_run)
	@d=1; prog=makenf; $(check_run)
	@d=1; prog=nftest; $(check_run)
	@d=1; prog=nflist; $(check_run)
	@d=1; prog=nflist_loop; $(check_run)
	@d=1; prog=dimtabnew; $(check_run)
	@d=1; prog=dimtabtwist; $(check_run)
	@d=1; prog=moreap; $(check_run)
	@d=1; prog=moreap1; $(check_run)
	@d=1; prog=modularity; $(check_run)
	@d=1; prog=modularity_modp; $(check_run)
	@d=4; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_2: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=8; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=2; prog=makenf_loop; $(check_run)
	@d=2; prog=makenf; $(check_run)
	@d=2; prog=nftest; $(check_run)
	@d=2; prog=nflist; $(check_run)
	@d=2; prog=nflist_loop; $(check_run)
	@d=2; prog=dimtabnew; $(check_run)
	@d=2; prog=dimtabtwist; $(check_run)
	@d=2; prog=moreap; $(check_run)
	@d=2; prog=moreap1; $(check_run)
	@d=2; prog=modularity; $(check_run)
	@d=2; prog=modularity_modp; $(check_run)
	@d=8; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_3: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=3; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=3; prog=makenf_loop; $(check_run)
	@d=3; prog=makenf; $(check_run)
	@d=3; prog=nftest; $(check_run)
	@d=3; prog=nflist; $(check_run)
	@d=3; prog=nflist_loop; $(check_run)
	@d=3; prog=dimtabnew; $(check_run)
	@d=3; prog=dimtabtwist; $(check_run)
	@d=3; prog=moreap; $(check_run)
	@d=3; prog=moreap1; $(check_run)
	@d=3; prog=modularity; $(check_run)
	@d=3; prog=modularity_modp; $(check_run)
	@d=3; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_7: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=7; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=7; prog=makenf_loop; $(check_run)
	@d=7; prog=makenf; $(check_run)
	@d=7; prog=nftest; $(check_run)
	@d=7; prog=nflist; $(check_run)
	@d=7; prog=nflist_loop; $(check_run)
	@d=7; prog=dimtabnew; $(check_run)
	@d=7; prog=dimtabtwist; $(check_run)
	@d=7; prog=moreap; $(check_run)
	@d=7; prog=moreap1; $(check_run)
	@d=7; prog=modularity; $(check_run)
	@d=7; prog=modularity_modp; $(check_run)
	@d=7; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_11: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=11; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=11; prog=makenf_loop; $(check_run)
	@d=11; prog=makenf; $(check_run)
	@d=11; prog=nftest; $(check_run)
	@d=11; prog=nflist; $(check_run)
	@d=11; prog=nflist_loop; $(check_run)
	@d=11; prog=dimtabnew; $(check_run)
	@d=11; prog=dimtabtwist; $(check_run)
	@d=11; prog=moreap; $(check_run)
	@d=11; prog=moreap1; $(check_run)
	@d=11; prog=modularity; $(check_run)
	@d=11; prog=modularity_modp; $(check_run)
	@d=11; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_19: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=19; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=19; prog=makenf_loop; $(check_run)
	@d=19; prog=makenf; $(check_run)
	@d=19; prog=nftest; $(check_run)
	@d=19; prog=nflist; $(check_run)
	@d=19; prog=nflist_loop; $(check_run)
	@d=19; prog=dimtabnew; $(check_run)
	@d=19; prog=dimtabtwist; $(check_run)
	@d=19; prog=moreap; $(check_run)
	@d=19; prog=moreap1; $(check_run)
	@d=19; prog=modularity; $(check_run)
	@d=19; prog=modularity_modp; $(check_run)
	@d=19; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_43: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=43; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=43; prog=makenf_loop; $(check_run)
	@d=43; prog=makenf; $(check_run)
	@d=43; prog=nftest; $(check_run)
	@d=43; prog=nflist; $(check_run)
	@d=43; prog=nflist_loop; $(check_run)
	@d=43; prog=dimtabnew; $(check_run)
	@d=43; prog=dimtabtwist; $(check_run)
	@d=43; prog=moreap; $(check_run)
	@d=43; prog=moreap1; $(check_run)
	@d=43; prog=modularity; $(check_run)
	@d=43; prog=modularity_modp; $(check_run)
	@d=43; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_67: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=67; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=67; prog=makenf_loop; $(check_run)
	@d=67; prog=makenf; $(check_run)
	@d=67; prog=nftest; $(check_run)
	@d=67; prog=nflist; $(check_run)
	@d=67; prog=nflist_loop; $(check_run)
	@d=67; prog=dimtabnew; $(check_run)
	@d=67; prog=dimtabtwist; $(check_run)
	@d=67; prog=moreap; $(check_run)
	@d=67; prog=moreap1; $(check_run)
	@d=67; prog=modularity; $(check_run)
	@d=67; prog=modularity_modp; $(check_run)
	@d=67; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_163: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=163; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=163; prog=makenf_loop; $(check_run)
	@d=163; prog=makenf; $(check_run)
	@d=163; prog=nftest; $(check_run)
	@d=163; prog=nflist; $(check_run)
	@d=163; prog=nflist_loop; $(check_run)
	@d=163; prog=dimtabnew; $(check_run)
	@d=163; prog=dimtabtwist; $(check_run)
	@d=163; prog=moreap; $(check_run)
	@d=163; prog=moreap1; $(check_run)
	@d=163; prog=modularity; $(check_run)
	@d=163; prog=modularity_modp; $(check_run)
	@d=163; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_23: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=23; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=23; prog=makenf_loop; $(check_run)
	@d=23; prog=makenf; $(check_run)
	@d=23; prog=nftest; $(check_run)
	@d=23; prog=nflist; $(check_run)
	@d=23; prog=nflist_loop; $(check_run)
	@d=23; prog=dimtabnew; $(check_run)
	@d=23; prog=dimtabtwist; $(check_run)
	@d=23; prog=moreap; $(check_run)
	@d=23; prog=moreap1; $(check_run)
	@d=23; prog=modularity; $(check_run)
	@d=23; prog=modularity_modp; $(check_run)
	@d=23; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_31: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=31; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=31; prog=makenf_loop; $(check_run)
	@d=31; prog=makenf; $(check_run)
	@d=31; prog=nftest; $(check_run)
	@d=31; prog=nflist; $(check_run)
	@d=31; prog=nflist_loop; $(check_run)
	@d=31; prog=dimtabnew; $(check_run)
	@d=31; prog=dimtabtwist; $(check_run)
	@d=31; prog=moreap; $(check_run)
	@d=31; prog=moreap1; $(check_run)
	@d=31; prog=modularity; $(check_run)
	@d=31; prog=modularity_modp; $(check_run)
	@d=31; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_47: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=47; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=47; prog=makenf_loop; $(check_run)
	@d=47; prog=makenf; $(check_run)
	@d=47; prog=nftest; $(check_run)
	@d=47; prog=nflist; $(check_run)
	@d=47; prog=nflist_loop; $(check_run)
	@d=47; prog=dimtabnew; $(check_run)
	@d=47; prog=dimtabtwist; $(check_run)
	@d=47; prog=moreap; $(check_run)
	@d=47; prog=moreap1; $(check_run)
	@d=47; prog=modularity; $(check_run)
	@d=47; prog=modularity_modp; $(check_run)
	@d=47; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_59: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=59; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=59; prog=makenf_loop; $(check_run)
	@d=59; prog=makenf; $(check_run)
	@d=59; prog=nftest; $(check_run)
	@d=59; prog=nflist; $(check_run)
	@d=59; prog=nflist_loop; $(check_run)
	@d=59; prog=dimtabnew; $(check_run)
	@d=59; prog=dimtabtwist; $(check_run)
	@d=59; prog=moreap; $(check_run)
	@d=59; prog=moreap1; $(check_run)
	@d=59; prog=modularity; $(check_run)
	@d=59; prog=modularity_modp; $(check_run)
	@d=59; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_71: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=71; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=71; prog=makenf_loop; $(check_run)
	@d=71; prog=makenf; $(check_run)
	@d=71; prog=nftest; $(check_run)
	@d=71; prog=nflist; $(check_run)
	@d=71; prog=nflist_loop; $(check_run)
	@d=71; prog=dimtabnew; $(check_run)
	@d=71; prog=dimtabtwist; $(check_run)
	@d=71; prog=moreap; $(check_run)
	@d=71; prog=moreap1; $(check_run)
	@d=71; prog=modularity; $(check_run)
	@d=71; prog=modularity_modp; $(check_run)
	@d=71; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_79: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=79; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=79; prog=makenf_loop; $(check_run)
	@d=79; prog=makenf; $(check_run)
	@d=79; prog=nftest; $(check_run)
	@d=79; prog=nflist; $(check_run)
	@d=79; prog=nflist_loop; $(check_run)
	@d=79; prog=dimtabnew; $(check_run)
	@d=79; prog=dimtabtwist; $(check_run)
	@d=79; prog=moreap; $(check_run)
	@d=79; prog=moreap1; $(check_run)
	@d=79; prog=modularity; $(check_run)
	@d=79; prog=modularity_modp; $(check_run)
	@d=79; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_83: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=83; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=83; prog=makenf_loop; $(check_run)
	@d=83; prog=makenf; $(check_run)
	@d=83; prog=nftest; $(check_run)
	@d=83; prog=nflist; $(check_run)
	@d=83; prog=nflist_loop; $(check_run)
	@d=83; prog=dimtabnew; $(check_run)
	@d=83; prog=dimtabtwist; $(check_run)
	@d=83; prog=moreap; $(check_run)
	@d=83; prog=moreap1; $(check_run)
	@d=83; prog=modularity; $(check_run)
	@d=83; prog=modularity_modp; $(check_run)
	@d=83; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_5: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=20; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=5; prog=makenf_loop; $(check_run)
	@d=5; prog=makenf; $(check_run)
	@d=5; prog=nftest; $(check_run)
	@d=5; prog=nflist; $(check_run)
	@d=5; prog=nflist_loop; $(check_run)
	@d=5; prog=dimtabnew; $(check_run)
	@d=5; prog=dimtabtwist; $(check_run)
	@d=5; prog=moreap; $(check_run)
	@d=5; prog=moreap1; $(check_run)
	@d=5; prog=modularity; $(check_run)
	@d=5; prog=modularity_modp; $(check_run)
	@d=20; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_14: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=56; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=14; prog=makenf_loop; $(check_run)
	@d=14; prog=makenf; $(check_run)
	@d=14; prog=nftest; $(check_run)
	@d=14; prog=nflist; $(check_run)
	@d=14; prog=nflist_loop; $(check_run)
	@d=14; prog=dimtabnew; $(check_run)
	@d=14; prog=dimtabtwist; $(check_run)
	@d=14; prog=moreap; $(check_run)
	@d=14; prog=moreap1; $(check_run)
	@d=14; prog=modularity; $(check_run)
	@d=14; prog=modularity_modp; $(check_run)
	@d=56; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_21: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=84; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=21; prog=makenf_loop; $(check_run)
	@d=21; prog=makenf; $(check_run)
	@d=21; prog=nftest; $(check_run)
	@d=21; prog=nflist; $(check_run)
	@d=21; prog=nflist_loop; $(check_run)
	@d=21; prog=dimtabnew; $(check_run)
	@d=21; prog=dimtabtwist; $(check_run)
	@d=21; prog=moreap; $(check_run)
	@d=21; prog=moreap1; $(check_run)
	@d=21; prog=modularity; $(check_run)
	@d=21; prog=modularity_modp; $(check_run)
	@d=84; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_95: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1 modularity modularity_modp
	@d=95; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=95; prog=makenf_loop; $(check_run)
	@d=95; prog=makenf; $(check_run)
	@d=95; prog=nftest; $(check_run)
	@d=95; prog=nflist; $(check_run)
	@d=95; prog=nflist_loop; $(check_run)
	@d=95; prog=dimtabnew; $(check_run)
	@d=95; prog=dimtabtwist; $(check_run)
	@d=95; prog=moreap; $(check_run)
	@d=95; prog=moreap1; $(check_run)
	@d=95; prog=modularity; $(check_run)
	@d=95; prog=modularity_modp; $(check_run)
	@d=95; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_6: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=24; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=6; prog=makenf_loop; $(check_run)
	@d=6; prog=makenf; $(check_run)
	@d=6; prog=nftest; $(check_run)
	@d=6; prog=nflist; $(check_run)
	@d=6; prog=nflist_loop; $(check_run)
	@d=6; prog=dimtabnew; $(check_run)
	@d=6; prog=dimtabtwist; $(check_run)
	@d=6; prog=moreap; $(check_run)
	@d=6; prog=moreap1; $(check_run)
	@d=24; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_10: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=40; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=10; prog=makenf_loop; $(check_run)
	@d=10; prog=makenf; $(check_run)
	@d=10; prog=nftest; $(check_run)
	@d=10; prog=nflist; $(check_run)
	@d=10; prog=nflist_loop; $(check_run)
	@d=10; prog=dimtabnew; $(check_run)
	@d=10; prog=dimtabtwist; $(check_run)
	@d=10; prog=moreap; $(check_run)
	@d=10; prog=moreap1; $(check_run)
	@d=40; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_13: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=52; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=13; prog=makenf_loop; $(check_run)
	@d=13; prog=makenf; $(check_run)
	@d=13; prog=nftest; $(check_run)
	@d=13; prog=nflist; $(check_run)
	@d=13; prog=nflist_loop; $(check_run)
	@d=13; prog=dimtabnew; $(check_run)
	@d=13; prog=dimtabtwist; $(check_run)
	@d=13; prog=moreap; $(check_run)
	@d=13; prog=moreap1; $(check_run)
	@d=52; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_15: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=15; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=15; prog=makenf_loop; $(check_run)
	@d=15; prog=makenf; $(check_run)
	@d=15; prog=nftest; $(check_run)
	@d=15; prog=nflist; $(check_run)
	@d=15; prog=nflist_loop; $(check_run)
	@d=15; prog=dimtabnew; $(check_run)
	@d=15; prog=dimtabtwist; $(check_run)
	@d=15; prog=moreap; $(check_run)
	@d=15; prog=moreap1; $(check_run)
	@d=15; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_17: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=68; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=17; prog=makenf_loop; $(check_run)
	@d=17; prog=makenf; $(check_run)
	@d=17; prog=nftest; $(check_run)
	@d=17; prog=nflist; $(check_run)
	@d=17; prog=nflist_loop; $(check_run)
	@d=17; prog=dimtabnew; $(check_run)
	@d=17; prog=dimtabtwist; $(check_run)
	@d=17; prog=moreap; $(check_run)
	@d=17; prog=moreap1; $(check_run)
	@d=68; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_22: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=88; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=22; prog=makenf_loop; $(check_run)
	@d=22; prog=makenf; $(check_run)
	@d=22; prog=nftest; $(check_run)
	@d=22; prog=nflist; $(check_run)
	@d=22; prog=nflist_loop; $(check_run)
	@d=22; prog=dimtabnew; $(check_run)
	@d=22; prog=dimtabtwist; $(check_run)
	@d=22; prog=moreap; $(check_run)
	@d=22; prog=moreap1; $(check_run)
	@d=88; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_35: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=35; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=35; prog=makenf_loop; $(check_run)
	@d=35; prog=makenf; $(check_run)
	@d=35; prog=nftest; $(check_run)
	@d=35; prog=nflist; $(check_run)
	@d=35; prog=nflist_loop; $(check_run)
	@d=35; prog=dimtabnew; $(check_run)
	@d=35; prog=dimtabtwist; $(check_run)
	@d=35; prog=moreap; $(check_run)
	@d=35; prog=moreap1; $(check_run)
	@d=35; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_39: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=39; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=39; prog=makenf_loop; $(check_run)
	@d=39; prog=makenf; $(check_run)
	@d=39; prog=nftest; $(check_run)
	@d=39; prog=nflist; $(check_run)
	@d=39; prog=nflist_loop; $(check_run)
	@d=39; prog=dimtabnew; $(check_run)
	@d=39; prog=dimtabtwist; $(check_run)
	@d=39; prog=moreap; $(check_run)
	@d=39; prog=moreap1; $(check_run)
	@d=39; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_42: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=168; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=42; prog=makenf_loop; $(check_run)
	@d=42; prog=makenf; $(check_run)
	@d=42; prog=nftest; $(check_run)
	@d=42; prog=nflist; $(check_run)
	@d=42; prog=nflist_loop; $(check_run)
	@d=42; prog=dimtabnew; $(check_run)
	@d=42; prog=dimtabtwist; $(check_run)
	@d=42; prog=moreap; $(check_run)
	@d=42; prog=moreap1; $(check_run)
	@d=168; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_51: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=51; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=51; prog=makenf_loop; $(check_run)
	@d=51; prog=makenf; $(check_run)
	@d=51; prog=nftest; $(check_run)
	@d=51; prog=nflist; $(check_run)
	@d=51; prog=nflist_loop; $(check_run)
	@d=51; prog=dimtabnew; $(check_run)
	@d=51; prog=dimtabtwist; $(check_run)
	@d=51; prog=moreap; $(check_run)
	@d=51; prog=moreap1; $(check_run)
	@d=51; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_55: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=55; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=55; prog=makenf_loop; $(check_run)
	@d=55; prog=makenf; $(check_run)
	@d=55; prog=nftest; $(check_run)
	@d=55; prog=nflist; $(check_run)
	@d=55; prog=nflist_loop; $(check_run)
	@d=55; prog=dimtabnew; $(check_run)
	@d=55; prog=dimtabtwist; $(check_run)
	@d=55; prog=moreap; $(check_run)
	@d=55; prog=moreap1; $(check_run)
	@d=55; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_87: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=87; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=87; prog=makenf_loop; $(check_run)
	@d=87; prog=makenf; $(check_run)
	@d=87; prog=nftest; $(check_run)
	@d=87; prog=nflist; $(check_run)
	@d=87; prog=nflist_loop; $(check_run)
	@d=87; prog=dimtabnew; $(check_run)
	@d=87; prog=dimtabtwist; $(check_run)
	@d=87; prog=moreap; $(check_run)
	@d=87; prog=moreap1; $(check_run)
	@d=87; rm -rf $(NF_DIR)/2.0.$${d}.1

test_nf_91: makenf_loop makenf nftest nflist nflist_loop dimtabnew moreap moreap1
	@d=91; mkdir -p $(NF_DIR)/2.0.$${d}.1
	@d=91; prog=makenf_loop; $(check_run)
	@d=91; prog=makenf; $(check_run)
	@d=91; prog=nftest; $(check_run)
	@d=91; prog=nflist; $(check_run)
	@d=91; prog=nflist_loop; $(check_run)
	@d=91; prog=dimtabnew; $(check_run)
	@d=91; prog=dimtabtwist; $(check_run)
	@d=91; prog=moreap; $(check_run)
	@d=91; prog=moreap1; $(check_run)
	@d=91; rm -rf $(NF_DIR)/2.0.$${d}.1
