#!/bin/bash
d=$1
N=$2
NAP=100
VERBOSE=0
OUTPUT_EIGS=1
BOTH_CONJUGATES=1
FIRST_NORM=${N}
LAST_NORM=${N}

# Make sure newforms directory exists!

if [[ $((d % 4)) -ne 3 ]] ; then
    D=$(( 4*d ))
else
    D=$d
fi
mkdir -p newforms/2.0.${D}.1

PARAMS="${d} ${VERBOSE} ${NAP} ${OUTPUT_EIGS} ${BOTH_CONJUGATES} ${FIRST_NORM} ${LAST_NORM}"

PROG="./makenf_${d}_${N}"
ln -s makenf_loop "${PROG}"
echo "Running " ${PROG} " with parameters " ${PARAMS}
echo "${PARAMS}" | "${PROG}" > out/"${PROG}".out
echo "${PROG} completed"
/bin/rm "${PROG}"


# To use in parallel runs, one level norm per run:
#
# parallel -j 10 --progress ./makenf_hybrid 59 {1} ::: `seq 1 100`
