#!/bin/bash
d=$1
N=$2

NAP=100
VERBOSE=0

PARAMS="${d} ${VERBOSE} 1 ${NAP} 1 1 ${N} ${N}"

PROG="./makenf_l_${d}_${N}"
ln -s makenf_loop_long "${PROG}"

if (echo "${PARAMS}" | "${PROG}");
then
  echo "${PROG} using long ints succeeded"
  /bin/rm "${PROG}"
else
  echo "******************** ${PROG} using long ints FAILED, rerunning with ZZ *******************************"
  /bin/rm "${PROG}"
  PROG="./makenf_ZZ_${d}_${N}"
  ln -s makenf_loop_ZZ "${PROG}"
  echo "${PARAMS}" | "${PROG}"
  /bin/rm "${PROG}"
fi

# To use in parallel runs, one level norm per run:
#
# parallel -j 10 --progress ./makenf_hybrid 59 {1} ::: `seq 1101 1200`
