#!/bin/bash
d=$1
N=$2
NAP=100
VERBOSE=0
OUTPUT_EIGS=1
BOTH_CONJUGATES=1
FIRST_NORM=${N}
LAST_NORM=${N}

PARAMS="${d} ${VERBOSE} ${NAP} ${OUTPUT_EIGS} ${BOTH_CONJUGATES} ${FIRST_NORM} ${LAST_NORM}"

PROG="./makenf_long_${d}_${N}"
ln -s makenf_loop_long "${PROG}"

if ( echo "${PARAMS}" | "${PROG}" > "${PROG}".out );
then
  echo "${PROG} using long ints succeeded"
  /bin/rm "${PROG}"
else
  echo "******************** ${PROG} using long ints FAILED, rerunning with ZZ *******************************"
  /bin/rm "${PROG}"
  PROG="./makenf_ZZ_${d}_${N}"
  ln -s makenf_loop_ZZ "${PROG}"
  echo "${PARAMS}" | "${PROG}" > "${PROG}".out
  /bin/rm "${PROG}"
fi

# To use in parallel runs, one level norm per run:
#
# parallel -j 10 --progress ./makenf_hybrid 59 {1} ::: `seq 1 100`
